# Configuration Settings for LearnLive

import os
from dotenv import load_dotenv

load_dotenv()

# Server Configuration
SERVER_HOST = '0.0.0.0'  # Listen on all interfaces (for LAN)
SERVER_PORT = 8888
BUFFER_SIZE = 4096
MAX_CLIENTS = 50

# MongoDB Configuration
MONGODB_URI = os.getenv('MONGODB_URI', 'mongodb://localhost:27017/')
DATABASE_NAME = 'learnlive_db'

# Collections
USERS_COLLECTION = 'users'
CLASSES_COLLECTION = 'classes'
ASSIGNMENTS_COLLECTION = 'assignments'
SUBMISSIONS_COLLECTION = 'submissions'
ANNOUNCEMENTS_COLLECTION = 'announcements'
COMMENTS_COLLECTION = 'comments'
MATERIALS_COLLECTION = 'materials'

# Email Configuration (Gmail SMTP)
SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587
SMTP_EMAIL = os.getenv('SMTP_EMAIL', 'your-email@gmail.com')
SMTP_PASSWORD = os.getenv('SMTP_APP_PASSWORD', 'your-app-password')

# File Upload Configuration
UPLOAD_FOLDER = 'uploads'
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50 MB
ALLOWED_EXTENSIONS = {'pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'jpg', 'jpeg', 'png', 'zip'}

# Security
TOKEN_EXPIRY = 86400  # 24 hours in seconds
SECRET_KEY = os.getenv('SECRET_KEY', 'your-secret-key-change-in-production')

# Protocol Message Types
MSG_LOGIN = 'LOGIN'
MSG_SIGNUP = 'SIGNUP'
MSG_CREATE_CLASS = 'CREATE_CLASS'
MSG_JOIN_CLASS = 'JOIN_CLASS'
MSG_VIEW_CLASSES = 'VIEW_CLASSES'
MSG_CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT'
MSG_VIEW_ASSIGNMENTS = 'VIEW_ASSIGNMENTS'
MSG_SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT'
MSG_VIEW_SUBMISSIONS = 'VIEW_SUBMISSIONS'
MSG_GET_STUDENT_SUBMISSION = 'GET_STUDENT_SUBMISSION'
MSG_POST_ANNOUNCEMENT = 'POST_ANNOUNCEMENT'
MSG_VIEW_ANNOUNCEMENTS = 'VIEW_ANNOUNCEMENTS'
MSG_POST_COMMENT = 'POST_COMMENT'
MSG_VIEW_COMMENTS = 'VIEW_COMMENTS'
MSG_UPLOAD_FILE = 'UPLOAD_FILE'
MSG_DOWNLOAD_FILE = 'DOWNLOAD_FILE'
MSG_START_FILE_TRANSFER = 'START_FILE_TRANSFER'
MSG_FILE_CHUNK = 'FILE_CHUNK'
MSG_END_FILE_TRANSFER = 'END_FILE_TRANSFER'
MSG_CHUNK_ACK = 'CHUNK_ACK'
MSG_UPLOAD_COMPLETE_ACK = 'UPLOAD_COMPLETE_ACK'
MSG_REMOVE_STUDENT = 'REMOVE_STUDENT'
MSG_DELETE_CLASS = 'DELETE_CLASS'
MSG_VIEW_STUDENTS = 'VIEW_STUDENTS'
MSG_UPLOAD_MATERIAL = 'UPLOAD_MATERIAL'
MSG_VIEW_MATERIALS = 'VIEW_MATERIALS'
MSG_GET_TEACHER_SUBMISSIONS = 'GET_TEACHER_SUBMISSIONS'
MSG_GET_STUDENT_ALL_ASSIGNMENTS = 'GET_STUDENT_ALL_ASSIGNMENTS'
MSG_GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
MSG_POST_MESSAGE = 'POST_MESSAGE'
MSG_GET_MESSAGES = 'GET_MESSAGES'
MSG_MESSAGE_NOTIFICATION = 'MESSAGE_NOTIFICATION'

# Response Types
RESP_SUCCESS = 'SUCCESS'
RESP_ERROR = 'ERROR'
RESP_NOTIFICATION = 'NOTIFICATION'
